services:
  streamio-server:
    container_name: stremio-server
    image: stremio/server:latest
    ports:
      - 11470:11470
      # - 12470:12470
    networks:
      - dokploy-network
    expose:
      - 11470

networks:
  dokploy-network: