services:
  streamio-server:
    container_name: stremio-server
    image: stremio/server:latest
    ports:
      - 11470:11470
      # - 12470:12470
    networks:
      - dokploy-network
    expose:
      - 11470
    labels:
      - traefik.enable=true
      - traefik.http.routers.streamio-server.rule=Host(`streamio-server.valiantlynx.com`)
      - traefik.http.routers.streamio-server.entrypoints=web
      - traefik.http.services.streamio-server.loadbalancer.server.port=11470